fail_fast: true

repos:
  ### PYTHON

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
        language_version: python3.9
        additional_dependencies:
          - types-all
        args:
          - --ignore-missing-imports
          - --explicit-package-bases
        exclude: ^.*\b(migrations)\b.*$ # Django

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks: # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
      - id: black
        language_version: python3.8
        args:
          - --skip-string-normalization
        exclude: ^.*\b(migrations)\b.*$ # Django

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks: # https://beta.ruff.rs/docs/installation-and-usage/#usage
      - id: ruff
        args:
          - --show-source
          - --show-fixes
          - --fix

  ### MD

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix
        args:
          - --disable=line-length
          - --disable=no-inline-html

  ### MISC

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --skip=**/pnpm-lock.yaml

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.9.0
    hooks:
      - id: pretty-format-yaml
        args:
          - --offset=2
          - --preserve-quotes
          - --autofix

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # https://pre-commit.com/hooks.html
      # `(\S) - ` -> `$1 # `
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-ast # simply checks whether the files parse as valid python.
      - id: check-byte-order-marker # forbids files which have a utf-8 byte-order marker.
      - id: check-builtin-literals # requires literal syntax when initializing empty or zero python builtin types.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-docstring-first # checks a common error of defining a docstring after code.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-json # checks json files for parseable syntax.
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.
      - id: pretty-format-json # sets a standard for formatting json files.
        args:
          - --autofix
          - --indent=2
          - --no-sort-keys
          - --no-ensure-ascii
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-vcs-permalinks # ensures that links to vcs websites are permalinks.
      - id: check-xml # checks xml files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.
        args:
          - --allow-multiple-documents
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: destroyed-symlinks # detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      # - id: detect-aws-credentials # detects *your* aws credentials from the aws cli credentials file.
      - id: detect-private-key # detects the presence of private keys.
      - id: double-quote-string-fixer # replaces double quoted strings with single quoted strings.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: file-contents-sorter # sorts the lines in specified files (defaults to alphabetical). you must provide list of target files as input in your .pre-commit-config.yaml file.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      # - id: fix-encoding-pragma # adds # -*- coding: utf-8 -*- to the top of python files.
      - id: forbid-new-submodules # prevents addition of new git submodules.
      - id: forbid-submodules # forbids any submodules in the repository
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: name-tests-test # verifies that test files are named correctly.
        args:
          - --pytest-test-first
      # - id: no-commit-to-branch # don't commit to branch
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: sort-simple-yaml # sorts simple yaml files which consist only of top-level keys, preserving comments and blocks.
      - id: trailing-whitespace # trims trailing whitespace.
